/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Definition2121

#doc (Manual) "Symmetric algebra, exterior algebra, and universal enveloping algebra (coordinate-free)" =>
# Symmetric algebra, exterior algebra, and universal enveloping algebra (coordinate-free)
%%%
tag := "Chapter2/Definition2.12.1"
number := false
%%%
$`x_1, \ldots, x_N` in $`V` defines an isomorphism of $`TV` with the free algebra $`k\langle x_1, \ldots, x_n \rangle`.

Also, one can make the following definition.

*Definition 2.12.1.* (i) The *symmetric algebra* $`SV` of $`V` is the quotient of $`TV` by the ideal generated by $`v \otimes w - w \otimes v`, $`v, w \in V`.

(ii) The *exterior algebra* $`\wedge V` of $`V` is the quotient of $`TV` by the ideal generated by $`v \otimes v`, $`v \in V`.

(iii) If $`V` is a Lie algebra, the *universal enveloping algebra* $`\mathcal{U}(V)` of $`V` is the quotient of $`TV` by the ideal generated by $`v \otimes w - w \otimes v - [v, w]`, $`v, w \in V`.

It is easy to see that a choice of a basis $`x_1, \ldots, x_N` in $`V` identifies $`SV` with the polynomial algebra $`k[x_1, \ldots, x_N]`, $`\wedge V` with the exterior algebra $`\wedge_k(x_1, \ldots, x_N)`, and the universal enveloping algebra $`\mathcal{U}(V)` with one defined previously.

Moreover, it is easy to see that we have decompositions

$$`SV = \bigoplus_{n \geq 0} S^n V, \quad \wedge V = \bigoplus_{n \geq 0} \wedge^n V.`

## Formalization
%%%
tag := "Chapter2/Definition2.12.1/formalization"
number := false
%%%

### Primary declarations

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.ExteriorAlgebra.auxiliaryModelDirectSumEquiv}

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.ExteriorAlgebra.auxiliaryModelEquivFinsupp}

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.SymmetricAlgebra.auxiliaryModelDirectSumEquiv}

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.SymmetricAlgebra.auxiliaryModelEquivMvPolynomial}

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.UniversalEnvelopingAlgebra.auxiliaryBasisEquiv}

### Supporting declarations

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.ExteriorAlgebra.auxiliaryModel}

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.ExteriorAlgebra.generator_sq_eq_zero}

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.SymmetricAlgebra.auxiliaryModel}

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.SymmetricAlgebra.generator_mul_comm}

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.UniversalEnvelopingAlgebra.auxiliaryType}

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.UniversalEnvelopingAlgebra.generator_commutator}
