/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Definition299

#doc (Manual) "Universal enveloping algebra" =>
# Universal enveloping algebra
%%%
tag := "Chapter2/Definition2.9.9"
number := false
%%%
*Definition 2.9.9.* Let $`\mathfrak{g}` be a Lie algebra with basis $`x_i` and $`[\ ,\ ]` defined by $`[x_i, x_j] = \sum_k c^k_{ij} x_k`. The *universal enveloping algebra* $`U(\mathfrak{g})` is the associative algebra generated by the $`x_i`'s with the defining relations $`x_i x_j - x_j x_i = \sum_k c^k_{ij} x_k`.

## Formalization
%%%
tag := "Chapter2/Definition2.9.9/formalization"
number := false
%%%

### Supporting declarations

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.UniversalEnvelopingAlgebra.auxiliaryBasisEquiv}

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.UniversalEnvelopingAlgebra.auxiliaryBasisPairElement}

{Manual.docstring RepresentationTheory.Algebra.AuxiliaryLieModuleConstructions.UniversalEnvelopingAlgebra.auxiliaryBasisType}

{Manual.docstring RepresentationTheory.Algebra.Lie.AssociatedTypes.LieAlgebra.AuxiliaryType}
