/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Discussion27Intro

#doc (Manual) "Section 2.7: Examples of algebras \u2014 Weyl algebra and q-Weyl algebra" =>
# Section 2.7: Examples of algebras — Weyl algebra and q-Weyl algebra
%%%
tag := "Chapter2/Discussion_2.7_intro"
number := false
%%%

## 2.7. Examples of algebras
%%%
tag := "Chapter2/Discussion_2.7_intro/heading-1"
%%%

The following two examples are among the simplest interesting examples of noncommutative associative algebras:

(1) the *Weyl algebra*, $`k\langle x, y \rangle / \langle yx - xy - 1 \rangle`;

(2) the *$`q`-Weyl algebra*, generated by $`x, x^{-1}, y, y^{-1}` with defining relations $`yx = qxy` and $`xx^{-1} = x^{-1}x = yy^{-1} = y^{-1}y = 1`.

## Formalization
%%%
tag := "Chapter2/Discussion_2.7_intro/formalization"
number := false
%%%

### Supporting declarations

{Manual.docstring RepresentationTheory.Algebra.Module.TwistedLatticeShifts.auxiliaryFour}

{Manual.docstring RepresentationTheory.Algebra.Module.TwistedLatticeShifts.auxiliaryOne}

{Manual.docstring RepresentationTheory.Algebra.Module.TwistedLatticeShifts.auxiliaryThree}

{Manual.docstring RepresentationTheory.Algebra.Module.TwistedLatticeShifts.auxiliaryTwo}

{Manual.docstring RepresentationTheory.Algebra.Module.TwistedLatticeShifts.twistedLatticeShiftSubalgebra}

{Manual.docstring RepresentationTheory.Algebra.Module.TwistedLatticeShifts.twistedLatticeShift_generators_commute_up_to_unit}

{Manual.docstring RepresentationTheory.FreeAlgebra.PolynomialOperators.AuxiliaryAlgebra}

{Manual.docstring RepresentationTheory.FreeAlgebra.PolynomialOperators.AuxiliaryAlgebra.secondOperator_mul_firstOperator}
