/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Example2912

#doc (Manual) "Universal enveloping algebra of sl(2)" =>
# Universal enveloping algebra of sl(2)
%%%
tag := "Chapter2/Example2.9.12"
number := false
%%%
*Example 2.9.12.* The associative algebra $`U(\mathfrak{sl}(2))` is the algebra generated by $`e`, $`f`, $`h`, with relations

$$`he - eh = 2e, \qquad hf - fh = -2f, \qquad ef - fe = h.`

## Formalization
%%%
tag := "Chapter2/Example2.9.12/formalization"
number := false
%%%

### Primary declarations

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.lieEquiv}

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.matrix_eq_aux1}

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.matrix_eq_aux2}

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.nontrivial}

### Supporting declarations

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.PresentedAlgebra}

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.algEquiv}

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.distinguished_ne_zero_aux1}

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.enveloping_commutator_relations}

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.map_apply_aux1}

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.map_apply_aux2}

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.map_apply_aux3}

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.matrix_basis2}

{Manual.docstring RepresentationTheory.LieAlgebra.SpecialLinearPresentation.nontrivial_aux1}
