/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Example2913

#doc (Manual) "Universal enveloping algebra of the Heisenberg Lie algebra" =>
# Universal enveloping algebra of the Heisenberg Lie algebra
%%%
tag := "Chapter2/Example2.9.13"
number := false
%%%
*Example 2.9.13.* The algebra $`U(\mathcal{H})`, where $`\mathcal{H}` is the Heisenberg Lie algebra, is the algebra generated by $`x`, $`y`, $`c` with the relations

$$`yx - xy = c, \qquad yc - cy = 0, \qquad xc - cx = 0.`

Note that the Weyl algebra is the quotient of $`U(\mathcal{H})` by the relation $`c = 1`.

## Formalization
%%%
tag := "Chapter2/Example2.9.13/formalization"
number := false
%%%

### Primary declarations

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.algEquiv}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.enveloping_commutator_relations}

### Supporting declarations

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.AuxiliaryType}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.AuxiliaryType_aux1}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.AuxiliaryType_aux2}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.bracket_eq_aux1}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.bracket_eq_aux2}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.bracket_eq_aux3}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.distinguishedElement_aux2}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.distinguishedElement_aux5}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.distinguishedElement_aux6}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.exists_witness}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.map_apply_aux14}

{Manual.docstring RepresentationTheory.LieAlgebra.ThreeGeneratorPresentations.weylQuotientEquiv}
