/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Problem2165

#doc (Manual) "Quantum enveloping algebra U\\_q(sl(2)) and its irreducible representations" =>
# Quantum enveloping algebra U\_q(sl(2)) and its irreducible representations
%%%
tag := "Chapter2/Problem2.16.5"
number := false
%%%
*Problem 2.16.5.* Let $`k` be an algebraically closed field of characteristic zero, and let $`q \in k^\times`, $`q \neq \pm 1`. The quantum enveloping algebra $`\mathcal{U}_q(\mathfrak{sl}(2))` is the algebra generated by $`e, f, K, K^{-1}` with relations

$$`KeK^{-1} = q^2 e, \quad KfK^{-1} = q^{-2} f, \quad [e, f] = \frac{K - K^{-1}}{q - q^{-1}}`

(if you formally set $`K = q^h`, you'll see that this algebra, in an appropriate sense, "degenerates" to $`\mathcal{U}(\mathfrak{sl}(2))` as $`q \to 1`). Classify irreducible
representations of $`\mathcal{U}_q(\mathfrak{sl}(2))`. Consider separately the cases of $`q` being a root of unity and $`q` not being a root of unity.

## Formalization
%%%
tag := "Chapter2/Problem2.16.5/formalization"
number := false
%%%

### Primary declarations

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.exists_highestWeightVector_eigenvalue_eq_sign_mul_pow}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.exists_ne_zero_raising_annihilated_weightEigenvector}

### Supporting declarations

Declaration: IsOfFinOrder

Alignment metadata: book-ref=Chapter2/Problem2.16.5; role=supporting

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.QuantumEnvelopingAlgebra}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.Relations}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.complexCharacter_surjective}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.finrank_le_orderOf}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.inverseWeightElement_mul_weightElement}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.loweringElement_order_pow_smul_eq_scalar}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.parameterDifference_smul_commutator}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.raisingElement_order_pow_smul_eq_scalar}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.weightActionEnd_structure_of_finiteOrder}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.weightElement_mul_inverseWeightElement}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.weightElement_mul_loweringElement}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.weightElement_mul_raisingElement}

{Manual.docstring RepresentationTheory.Algebra.ParameterizedComplexRelations.weightElement_order_pow_smul_eq_scalar}
