/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Remark2114

#doc (Manual) "Tensor product over a ring" =>
# Tensor product over a ring
%%%
tag := "Chapter2/Remark2.11.4"
number := false
%%%
*Remark 2.11.4.* Note that a similar definition to the above can be used to define the tensor product $`V \otimes_A W`, where $`A` is any ring, $`V` is a right $`A`-module, and $`W` is a left $`A`-module. Namely, $`V \otimes_A W` is the abelian group which is the quotient of the group $`V \bullet W` freely generated by formal symbols $`v \otimes w`, $`v \in V`, $`w \in W`, modulo the
relations

$$`
(v_1 + v_2) \otimes w - v_1 \otimes w - v_2 \otimes w,
`
$$`
v \otimes (w_1 + w_2) - v \otimes w_1 - v \otimes w_2,
`
$$`
va \otimes w - v \otimes aw, \quad a \in A.
`

## Formalization
%%%
tag := "Chapter2/Remark2.11.4/formalization"
number := false
%%%

### Supporting declarations

{Manual.docstring RepresentationTheory.Algebra.Module.BalancedTensorProduct.Auxiliary}

{Manual.docstring RepresentationTheory.Algebra.Module.BalancedTensorProduct.Auxiliary.add_left}

{Manual.docstring RepresentationTheory.Algebra.Module.BalancedTensorProduct.Auxiliary.add_right}

{Manual.docstring RepresentationTheory.Algebra.Module.BalancedTensorProduct.Auxiliary.mk}

{Manual.docstring RepresentationTheory.Algebra.Module.BalancedTensorProduct.Auxiliary.op_smul_left_eq_smul_right}
