#!/usr/bin/env python3
"""Materialize the staged Lean and Verso releases into clean repositories.

This script is deliberately a staging-only operation.  It never contacts a
Git remote and it never modifies the staged source trees.  The caller chooses
two empty destinations and supplies the Git URL and revision that the private
Verso repository should use for the public Lean formalization dependency.  In
the clean-history publication mode it can create the public root commit first
and derive that exact revision before creating the private root commit.

The generated repositories omit local Lake state and rendered output.  In
particular, ``lake-manifest.json`` is deliberately regenerated by ``lake
update``: the staged manifest contains local ``path`` dependencies that must
not escape into a publishable repository.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parent
CLEAN_SOURCE = ROOT / "clean-code" / "release"
VERSO_SOURCE = ROOT / "verso" / "release"
BOOK_BLOBS = ROOT / "verso" / "source-markdown"
CLEANROOM_PROPOSALS = ROOT / "manifests" / "alignment" / "cleanroom-proposals.jsonl"
ADJUDICATED_EDGES = ROOT / "manifests" / "alignment" / "adjudicated-alignment-edges.jsonl"
SOURCE_NODES = ROOT / "manifests" / "alignment" / "source-nodes.jsonl"

# These are release-local artifacts, not source.  lake-manifest.json is also
# excluded because the staged Verso manifest records two unavailable local
# path dependencies.  The materialized lakefile pins both public Git inputs,
# and `lake update` produces the new lock file.
EXCLUDED_DIRECTORIES = frozenset({".git", ".lake", ".verso", "_out", "__pycache__"})
EXCLUDED_FILES = frozenset(
    {"alignment-export.json", "lake-manifest.json", "outputs.jsonl"}
)
EXCLUDED_SUFFIXES = frozenset({".olean", ".ilean"})
EXCLUDED_SUBTREES = frozenset(
    {Path("IntroductionToRepresentationTheoryVerso/Spike")}
)
PROCESS_ROOTS = frozenset(
    {
        "alignment-adjudication-packets",
        "clean-room-packets",
        "conversion-packets",
        "manifests",
        "reports",
    }
)

DEFAULT_VERSO_GIT_URL = "https://github.com/leanprover/verso.git"
DEFAULT_VERSO_GIT_REV = "e09d21a5f7f66c9fc985b73197708298569bf583"
DEFAULT_CLEAN_GIT_URL = (
    "https://github.com/mathlib-initiative/EtingofRepresentationTheory.git"
)
CANONICAL_GIT_REVISION = re.compile(r"[0-9a-f]{40}")


class MaterializationError(RuntimeError):
    """A requested output would be unsafe or would violate release policy."""


def require_canonical_clean_revision(revision: str) -> None:
    if CANONICAL_GIT_REVISION.fullmatch(revision) is None:
        raise MaterializationError(
            "--clean-git-rev must be an exact lowercase 40-hex commit revision"
        )


@dataclass(frozen=True)
class ReleaseTree:
    name: str
    source: Path
    destination: Path


def is_excluded(relative: Path) -> bool:
    """Return whether a source-relative path is a local/generated artifact."""
    if any(part in EXCLUDED_DIRECTORIES for part in relative.parts):
        return True
    if any(relative == subtree or subtree in relative.parents for subtree in EXCLUDED_SUBTREES):
        return True
    if relative.name in EXCLUDED_FILES or relative.suffix in EXCLUDED_SUFFIXES:
        return True
    return relative.parts and relative.parts[0] in PROCESS_ROOTS


def excluded_roots(source: Path) -> list[str]:
    """Report present exclusions as stable release-relative tree roots."""
    roots: set[str] = set()
    for path in sorted(source.rglob("*"), key=lambda path: path.as_posix()):
        relative = path.relative_to(source)
        if not is_excluded(relative):
            continue
        if relative.parent != Path(".") and is_excluded(relative.parent):
            continue
        roots.add(relative.as_posix() + "/" if path.is_dir() else relative.as_posix())
    return sorted(roots)


def retained_files(source: Path) -> list[str]:
    return sorted(
        path.relative_to(source).as_posix()
        for path in source.rglob("*")
        if path.is_file() and not is_excluded(path.relative_to(source))
    )


def ensure_source(source: Path) -> None:
    if not source.is_dir():
        raise MaterializationError(f"missing staged release source: {source}")


def ensure_empty_destination(destination: Path, sources: Iterable[Path]) -> None:
    resolved = destination.resolve()
    for source in sources:
        source_resolved = source.resolve()
        if resolved == source_resolved or source_resolved in resolved.parents:
            raise MaterializationError(
                f"destination must not be a staged source or a child of one: {destination}"
            )
    if destination.exists():
        if not destination.is_dir():
            raise MaterializationError(f"destination is not a directory: {destination}")
        if any(destination.iterdir()):
            raise MaterializationError(f"destination must be empty: {destination}")


def ensure_separate_destinations(lean_destination: Path, verso_destination: Path) -> None:
    """Reject output paths that could cause either materialization to overlap the other."""
    lean_resolved = lean_destination.resolve()
    verso_resolved = verso_destination.resolve()
    if (
        lean_resolved == verso_resolved
        or lean_resolved in verso_resolved.parents
        or verso_resolved in lean_resolved.parents
    ):
        raise MaterializationError(
            "Lean and Verso destinations must be distinct and neither may contain the other"
        )


def copy_release(source: Path, destination: Path) -> None:
    """Copy a source tree while excluding generated/local artifacts."""

    def ignore(directory: str, names: list[str]) -> set[str]:
        root = Path(directory)
        ignored: set[str] = set()
        for name in names:
            relative = (root / name).relative_to(source)
            if is_excluded(relative):
                ignored.add(name)
        return ignored

    # Preflight permits an existing empty directory, matching the CLI contract.
    shutil.copytree(
        source, destination, copy_function=shutil.copy2, ignore=ignore, dirs_exist_ok=True
    )


def toml_string(value: str) -> str:
    # JSON string escaping is valid TOML basic-string escaping for these fields.
    return json.dumps(value, ensure_ascii=False)


def write_clean_readme(destination: Path) -> None:
    shutil.copy2(CLEAN_SOURCE / "README.md", destination / "README.md")


def write_verso_readme(destination: Path) -> None:
    shutil.copy2(VERSO_SOURCE / "README.md", destination / "README.md")


def write_gitignore(destination: Path, *, verso: bool) -> None:
    lines = ["/.lake/", "/lake-manifest.json"]
    if verso:
        lines.extend(
            [
                "/_out/",
                "/.verso/",
                "/alignment-export.json",
                "/formalization-alignment.json",
            ]
        )
    else:
        lines.append("/outputs.jsonl")
    (destination / ".gitignore").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_verso_lakefile(
    destination: Path,
    clean_git_url: str,
    clean_git_rev: str,
    verso_git_url: str,
    verso_git_rev: str,
) -> None:
    require_canonical_clean_revision(clean_git_rev)
    (destination / "lakefile.toml").write_text(
        f'''name = "IntroductionToRepresentationTheoryVerso"
version = "0.1.0"
defaultTargets = ["IntroductionToRepresentationTheoryVerso", "book", "alignmentExport"]
enableArtifactCache = true

[[require]]
name = "verso"
git = {toml_string(verso_git_url)}
rev = {toml_string(verso_git_rev)}

[[require]]
name = "RepresentationTheoryFormalization"
git = {toml_string(clean_git_url)}
rev = {toml_string(clean_git_rev)}

[[lean_lib]]
name = "IntroductionToRepresentationTheoryVerso"

[[lean_exe]]
name = "book"
root = "Main"

[[lean_exe]]
name = "alignmentExport"
root = "AlignmentExport"
''',
        encoding="utf-8",
    )


def assert_materialized_tree(tree: ReleaseTree) -> None:
    actual = retained_files(tree.destination)
    expected = retained_files(tree.source)
    if actual != expected:
        missing = sorted(set(expected) - set(actual))
        unexpected = sorted(set(actual) - set(expected))
        raise MaterializationError(
            f"{tree.name}: copied tree differs from retained source files; "
            f"missing={missing[:5]}, unexpected={unexpected[:5]}"
        )
    for relative in actual:
        if is_excluded(Path(relative)):
            raise MaterializationError(f"{tree.name}: excluded artifact survived: {relative}")
        destination = tree.destination / relative
        if destination.is_symlink() or not destination.is_file():
            raise MaterializationError(
                f"{tree.name}: retained path is not a regular file: {relative}"
            )
    rewritten = (
        {".gitignore", "README.md"}
        if tree.name == "lean"
        else {".gitignore", "README.md", "lakefile.toml"}
    )
    for relative in sorted(set(actual) - rewritten):
        source = tree.source / relative
        destination = tree.destination / relative
        if source.read_bytes() != destination.read_bytes():
            raise MaterializationError(
                f"{tree.name}: retained file differs from staging: {relative}"
            )
        source_mode = stat.S_IMODE(source.stat().st_mode)
        destination_mode = stat.S_IMODE(destination.stat().st_mode)
        if source_mode != destination_mode:
            raise MaterializationError(
                f"{tree.name}: retained file mode differs from staging: {relative}: "
                f"{source_mode:o} != {destination_mode:o}"
            )


def assert_verso_dependency(
    destination: Path,
    clean_git_url: str,
    clean_git_rev: str,
    verso_git_url: str,
    verso_git_rev: str,
) -> None:
    require_canonical_clean_revision(clean_git_rev)
    lakefile = (destination / "lakefile.toml").read_text(encoding="utf-8")
    verso_stanza = (
        "[[require]]\n"
        'name = "verso"\n'
        f"git = {toml_string(verso_git_url)}\n"
        f"rev = {toml_string(verso_git_rev)}"
    )
    clean_stanza = (
        "[[require]]\n"
        'name = "RepresentationTheoryFormalization"\n'
        f"git = {toml_string(clean_git_url)}\n"
        f"rev = {toml_string(clean_git_rev)}"
    )
    try:
        config = tomllib.loads(lakefile)
    except tomllib.TOMLDecodeError as error:
        raise MaterializationError(f"Verso lakefile is not valid TOML: {error}") from error
    expected_dependencies = [
        {"name": "verso", "git": verso_git_url, "rev": verso_git_rev},
        {
            "name": "RepresentationTheoryFormalization",
            "git": clean_git_url,
            "rev": clean_git_rev,
        },
    ]
    if config.get("require") != expected_dependencies:
        raise MaterializationError(
            "Verso lakefile must contain only the exact requested Git dependencies"
        )
    if "enableArtifactCache = true" not in lakefile:
        raise MaterializationError("Verso lakefile does not enable the Lake artifact cache")
    if verso_stanza not in lakefile:
        raise MaterializationError("Verso lakefile lacks the requested pinned Verso Git dependency")
    if clean_stanza not in lakefile:
        raise MaterializationError("Verso lakefile lacks the requested pinned Lean Git dependency")
    if 'version = "0.1.0-private"' in lakefile:
        raise MaterializationError("Verso lakefile retained the staging-only private version suffix")
    if 'name = "RepresentationTheoryFormalization"\npath =' in lakefile:
        raise MaterializationError("Verso lakefile retained a local Lean path dependency")
    if (destination / "RepresentationTheoryFormalization").exists():
        raise MaterializationError("Verso release must not copy the Lean repository into itself")


def run_scanner(script: str, *arguments: Path) -> None:
    result = subprocess.run(
        [sys.executable, str(ROOT / script), *(str(value) for value in arguments)],
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        details = "\n".join(
            value.strip() for value in (result.stdout, result.stderr) if value.strip()
        )
        raise MaterializationError(f"{script} failed:\n{details}")


def validate_clean_source_and_destination(clean_destination: Path) -> None:
    """Run both scanners without shipping build state into the destination.

    The export scanner deliberately runs on the staged source because it
    validates built `.ilean` indexes. Those indexes are excluded release build
    cache. The leak scanner runs on both source and destination; byte-for-byte
    retained-file verification makes the source-built export result applicable
    to the destination.
    """

    run_scanner("scan_clean_release.py", CLEAN_SOURCE, BOOK_BLOBS)
    run_scanner("validate_clean_release_exports.py", CLEAN_SOURCE, CLEANROOM_PROPOSALS)
    run_scanner(
        "validate_clean_release_source_refs.py",
        CLEAN_SOURCE,
        CLEANROOM_PROPOSALS,
        ADJUDICATED_EDGES,
        SOURCE_NODES,
    )
    run_scanner("scan_clean_release.py", clean_destination, BOOK_BLOBS)


def validate_legal_metadata(
    clean_release: Path = CLEAN_SOURCE, verso_release: Path = VERSO_SOURCE
) -> None:
    run_scanner("validate_release_legal_metadata.py", clean_release, verso_release)


def validate_book_text_integrity(verso_release: Path = VERSO_SOURCE) -> None:
    run_scanner(
        "validate_book_text_integrity.py",
        verso_release / "metadata/items.json",
        verso_release / "source-markdown",
    )


def initialize_git(destination: Path) -> None:
    name = subprocess.run(
        ["git", "config", "--get", "user.name"], text=True, capture_output=True
    ).stdout.strip()
    email = subprocess.run(
        ["git", "config", "--get", "user.email"], text=True, capture_output=True
    ).stdout.strip()
    if not name or not email:
        raise MaterializationError(
            "--init-git needs configured git user.name and user.email for the initial commit"
        )
    source_date_epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if source_date_epoch is None:
        source_date_epoch = subprocess.run(
            ["git", "-C", str(ROOT), "show", "-s", "--format=%ct", "HEAD"],
            text=True,
            capture_output=True,
            check=True,
        ).stdout.strip()
    if not source_date_epoch.isascii() or not source_date_epoch.isdigit():
        raise MaterializationError(
            "SOURCE_DATE_EPOCH must be an unsigned integer when it is set"
        )
    commit_environment = os.environ.copy()
    commit_environment["GIT_AUTHOR_DATE"] = f"@{source_date_epoch} +0000"
    commit_environment["GIT_COMMITTER_DATE"] = f"@{source_date_epoch} +0000"
    subprocess.run(
        ["git", "init", "--initial-branch=main", str(destination)],
        check=True,
        text=True,
        capture_output=True,
    )
    subprocess.run(
        ["git", "-C", str(destination), "add", "-A"],
        check=True,
        text=True,
        capture_output=True,
    )
    subprocess.run(
        ["git", "-C", str(destination), "commit", "-m", "Initial release materialization"],
        check=True,
        text=True,
        capture_output=True,
        env=commit_environment,
    )


def git_head(destination: Path) -> str:
    revision = subprocess.run(
        ["git", "-C", str(destination), "rev-parse", "HEAD"],
        text=True,
        capture_output=True,
        check=True,
    ).stdout.strip()
    if len(revision) != 40 or any(character not in "0123456789abcdef" for character in revision):
        raise MaterializationError(f"could not derive a full Git revision from {destination}")
    return revision


def report_for(trees: list[ReleaseTree], *, dry_run: bool) -> dict[str, object]:
    return {
        "mode": "dry-run" if dry_run else "materialized",
        "trees": [
            {
                "name": tree.name,
                "source": str(tree.source),
                "destination": str(tree.destination),
                "retained_files": retained_files(tree.source),
                "excluded_tree_roots": excluded_roots(tree.source),
                "rewritten_files": (
                    [".gitignore", "README.md"]
                    if tree.name == "lean"
                    else [".gitignore", "README.md", "lakefile.toml"]
                ),
            }
            for tree in trees
        ],
        "validation": {
            "book_text_integrity": (
                "numeric page-order partition, exact single coverage, and span SHA-256"
            ),
            "leak_scanner": "source and materialized Lean tree",
            "export_scanner": "staged built Lean tree; destination build cache is excluded",
            "source_ref_scanner": "staged built Lean metadata against the adjudicated ledger",
            "legal_metadata": "both staged and materialized release trees",
            "retained_files": "regular files with staging-identical bytes and modes",
            "history": (
                "public root commit precedes the private root commit when "
                "--derive-clean-rev is used"
            ),
        },
    }


def tree_digest(root: Path) -> str:
    """Hash relative names, file modes, and bytes to prove repeatability."""
    digest = hashlib.sha256()
    for relative in retained_files(root):
        path = root / relative
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(f"{stat.S_IMODE(path.stat().st_mode):04o}".encode("ascii"))
        digest.update(b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def materialize(
    lean_destination: Path,
    verso_destination: Path,
    clean_git_url: str,
    clean_git_rev: str | None,
    verso_git_url: str,
    verso_git_rev: str,
    *,
    dry_run: bool,
    init_git: bool,
    derive_clean_rev: bool = False,
) -> dict[str, object]:
    if not clean_git_url.strip():
        raise MaterializationError("--clean-git-url must be nonempty")
    if derive_clean_rev:
        if not init_git:
            raise MaterializationError("--derive-clean-rev requires --init-git")
        if clean_git_rev is not None and clean_git_rev.strip():
            raise MaterializationError(
                "--derive-clean-rev cannot be combined with --clean-git-rev"
            )
    elif clean_git_rev is None:
        raise MaterializationError("--clean-git-rev must be provided")
    else:
        require_canonical_clean_revision(clean_git_rev)
    if not verso_git_url.strip() or not verso_git_rev.strip():
        raise MaterializationError("--verso-git-url and --verso-git-rev must be nonempty")
    for source in (CLEAN_SOURCE, VERSO_SOURCE, BOOK_BLOBS):
        ensure_source(source)
    for ledger in (CLEANROOM_PROPOSALS, ADJUDICATED_EDGES, SOURCE_NODES):
        if not ledger.is_file():
            raise MaterializationError(f"missing release validation ledger: {ledger}")

    trees = [
        ReleaseTree("lean", CLEAN_SOURCE, lean_destination),
        ReleaseTree("verso", VERSO_SOURCE, verso_destination),
    ]
    ensure_separate_destinations(lean_destination, verso_destination)
    for tree in trees:
        ensure_empty_destination(tree.destination, (CLEAN_SOURCE, VERSO_SOURCE))

    # Validate before any destination write, including in dry-run mode.
    run_scanner("scan_clean_release.py", CLEAN_SOURCE, BOOK_BLOBS)
    run_scanner("validate_clean_release_exports.py", CLEAN_SOURCE, CLEANROOM_PROPOSALS)
    run_scanner(
        "validate_clean_release_source_refs.py",
        CLEAN_SOURCE,
        CLEANROOM_PROPOSALS,
        ADJUDICATED_EDGES,
        SOURCE_NODES,
    )
    validate_legal_metadata()
    validate_book_text_integrity()
    report = report_for(trees, dry_run=dry_run)
    if dry_run:
        return report

    for tree in trees:
        copy_release(tree.source, tree.destination)

    write_gitignore(lean_destination, verso=False)
    write_clean_readme(lean_destination)
    write_gitignore(verso_destination, verso=True)
    write_verso_readme(verso_destination)
    resolved_clean_rev = clean_git_rev
    if not derive_clean_rev:
        assert resolved_clean_rev is not None
        write_verso_lakefile(
            verso_destination,
            clean_git_url,
            resolved_clean_rev,
            verso_git_url,
            verso_git_rev,
        )

    for tree in trees:
        assert_materialized_tree(tree)
    validate_clean_source_and_destination(lean_destination)
    validate_legal_metadata(lean_destination, verso_destination)
    validate_book_text_integrity(verso_destination)

    if init_git:
        initialize_git(lean_destination)
        if derive_clean_rev:
            resolved_clean_rev = git_head(lean_destination)
            write_verso_lakefile(
                verso_destination,
                clean_git_url,
                resolved_clean_rev,
                verso_git_url,
                verso_git_rev,
            )
    assert resolved_clean_rev is not None
    assert_verso_dependency(
        verso_destination,
        clean_git_url,
        resolved_clean_rev,
        verso_git_url,
        verso_git_rev,
    )
    if init_git:
        initialize_git(verso_destination)
    report["resolved_clean_git_rev"] = resolved_clean_rev
    return report


def self_test() -> dict[str, object]:
    """Exercise dry-run, safe destination handling, and deterministic materialization."""
    if not is_excluded(Path("outputs.jsonl")):
        raise MaterializationError("self-test did not exclude the public Lake mappings file")
    if not is_excluded(Path("alignment-export.json")):
        raise MaterializationError("self-test did not exclude the local alignment export")
    if is_excluded(Path("AlignmentExport.lean")):
        raise MaterializationError("self-test excluded the tracked alignment exporter")
    with tempfile.TemporaryDirectory(prefix="release-materialization-") as temp:
        root = Path(temp)
        lean_destination = root / "lean"
        verso_destination = root / "verso"
        kwargs = {
            "clean_git_url": DEFAULT_CLEAN_GIT_URL,
            "clean_git_rev": "0123456789abcdef0123456789abcdef01234567",
            "verso_git_url": DEFAULT_VERSO_GIT_URL,
            "verso_git_rev": DEFAULT_VERSO_GIT_REV,
            "init_git": False,
        }
        dry_report = materialize(
            lean_destination, verso_destination, dry_run=True, **kwargs
        )
        if lean_destination.exists() or verso_destination.exists():
            raise MaterializationError("dry-run created a destination")
        lean_destination.mkdir()
        verso_destination.mkdir()
        report = materialize(lean_destination, verso_destination, dry_run=False, **kwargs)
        for destination, forbidden in (
            (
                lean_destination,
                (".lake", ".verso", "_out", "lake-manifest.json", "outputs.jsonl"),
            ),
            (
                verso_destination,
                (
                    ".lake",
                    ".verso",
                    "_out",
                    "alignment-export.json",
                    "lake-manifest.json",
                ),
            ),
        ):
            if any((destination / name).exists() for name in forbidden):
                raise MaterializationError("self-test retained an excluded artifact")
        lean_gitignore = (lean_destination / ".gitignore").read_text(encoding="utf-8")
        if "/outputs.jsonl" not in lean_gitignore.splitlines():
            raise MaterializationError("self-test omitted the public outputs ignore rule")
        verso_gitignore = (verso_destination / ".gitignore").read_text(encoding="utf-8")
        if "/alignment-export.json" not in verso_gitignore.splitlines():
            raise MaterializationError("self-test omitted the private alignment-export ignore rule")
        if not (verso_destination / "AlignmentExport.lean").is_file():
            raise MaterializationError("self-test omitted the tracked alignment exporter")
        spike_trace = verso_destination / "IntroductionToRepresentationTheoryVerso" / "Spike"
        if spike_trace.exists():
            raise MaterializationError("self-test retained the excluded Spike process-trace directory")

        repeat_lean = root / "lean-repeat"
        repeat_verso = root / "verso-repeat"
        materialize(repeat_lean, repeat_verso, dry_run=False, **kwargs)
        if tree_digest(lean_destination) != tree_digest(repeat_lean):
            raise MaterializationError("self-test found a nondeterministic Lean release tree")
        if tree_digest(verso_destination) != tree_digest(repeat_verso):
            raise MaterializationError("self-test found a nondeterministic Verso release tree")
        updated_revision = "fedcba9876543210fedcba9876543210fedcba98"
        subprocess.run(
            [
                sys.executable,
                str(repeat_verso / "scripts" / "update_formalization_dependency.py"),
                updated_revision,
            ],
            check=True,
            text=True,
            capture_output=True,
        )
        assert_verso_dependency(
            repeat_verso,
            kwargs["clean_git_url"],
            updated_revision,
            kwargs["verso_git_url"],
            kwargs["verso_git_rev"],
        )
        blocked = root / "nonempty"
        blocked.mkdir()
        (blocked / "sentinel").write_text("do not overwrite\n", encoding="utf-8")
        try:
            materialize(blocked, root / "unused", dry_run=True, **kwargs)
        except MaterializationError as error:
            if "destination must be empty" not in str(error):
                raise
        else:
            raise MaterializationError("self-test accepted a nonempty destination")
        same_destination = root / "same"
        try:
            materialize(same_destination, same_destination, dry_run=True, **kwargs)
        except MaterializationError as error:
            if "must be distinct" not in str(error):
                raise
        else:
            raise MaterializationError("self-test accepted equal destinations")
        nested_lean = root / "nested"
        nested_verso = nested_lean / "verso"
        try:
            materialize(nested_lean, nested_verso, dry_run=True, **kwargs)
        except MaterializationError as error:
            if "neither may contain the other" not in str(error):
                raise
        else:
            raise MaterializationError("self-test accepted nested destinations")
        for option, invalid_kwargs in (
            ("--verso-git-url", {**kwargs, "verso_git_url": " "}),
            ("--verso-git-rev", {**kwargs, "verso_git_rev": ""}),
        ):
            try:
                materialize(
                    root / f"blank-{option[2:]}",
                    root / f"unused-{option[2:]}",
                    dry_run=True,
                    **invalid_kwargs,
                )
            except MaterializationError as error:
                if option not in str(error):
                    raise
            else:
                raise MaterializationError(f"self-test accepted an empty {option} override")
        for invalid_revision in (
            "0123456789abcdef",
            "ABCDEF0123456789ABCDEF0123456789ABCDEF01",
            "g123456789abcdef0123456789abcdef01234567",
        ):
            try:
                materialize(
                    root / "invalid-revision-lean",
                    root / "invalid-revision-verso",
                    dry_run=True,
                    **{**kwargs, "clean_git_rev": invalid_revision},
                )
            except MaterializationError as error:
                if "exact lowercase 40-hex" not in str(error):
                    raise
            else:
                raise MaterializationError(
                    "self-test accepted a noncanonical public revision"
                )
        derived_lean = root / "derived-lean"
        derived_verso = root / "derived-verso"
        derived = materialize(
            derived_lean,
            derived_verso,
            clean_git_url=DEFAULT_CLEAN_GIT_URL,
            clean_git_rev=None,
            verso_git_url=DEFAULT_VERSO_GIT_URL,
            verso_git_rev=DEFAULT_VERSO_GIT_REV,
            dry_run=False,
            init_git=True,
            derive_clean_rev=True,
        )
        derived_head = git_head(derived_lean)
        if derived.get("resolved_clean_git_rev") != derived_head:
            raise MaterializationError("self-test did not report the derived public root revision")
        assert_verso_dependency(
            derived_verso,
            DEFAULT_CLEAN_GIT_URL,
            derived_head,
            DEFAULT_VERSO_GIT_URL,
            DEFAULT_VERSO_GIT_REV,
        )
        repeat_derived_lean = root / "derived-lean-repeat"
        repeat_derived_verso = root / "derived-verso-repeat"
        materialize(
            repeat_derived_lean,
            repeat_derived_verso,
            clean_git_url=DEFAULT_CLEAN_GIT_URL,
            clean_git_rev=None,
            verso_git_url=DEFAULT_VERSO_GIT_URL,
            verso_git_rev=DEFAULT_VERSO_GIT_REV,
            dry_run=False,
            init_git=True,
            derive_clean_rev=True,
        )
        if git_head(repeat_derived_lean) != derived_head:
            raise MaterializationError(
                "self-test found a nondeterministic derived public root commit"
            )
        if git_head(repeat_derived_verso) != git_head(derived_verso):
            raise MaterializationError(
                "self-test found a nondeterministic derived private root commit"
            )
        return {
            "dry_run": dry_report,
            "materialized": report,
            "derived_clean_git_rev": derived_head,
            "self_test": "passed",
        }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lean-dest", type=Path)
    parser.add_argument("--verso-dest", type=Path)
    parser.add_argument("--clean-git-url", default=DEFAULT_CLEAN_GIT_URL)
    parser.add_argument("--clean-git-rev")
    parser.add_argument("--verso-git-url", default=DEFAULT_VERSO_GIT_URL)
    parser.add_argument("--verso-git-rev", default=DEFAULT_VERSO_GIT_REV)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--init-git",
        action="store_true",
        help="create one initial commit in each destination using configured Git identity",
    )
    parser.add_argument(
        "--derive-clean-rev",
        action="store_true",
        help=(
            "with --init-git, commit the public tree first and pin that exact root "
            "revision in the private Verso tree"
        ),
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="run dry-run and materialization checks in fresh temporary directories",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    try:
        if args.self_test:
            if any(
                value is not None
                for value in (args.lean_dest, args.verso_dest, args.clean_git_rev)
            ) or args.init_git or args.derive_clean_rev:
                raise MaterializationError(
                    "--self-test cannot be combined with destinations, clean Git inputs, or --init-git"
                )
            print(json.dumps(self_test(), ensure_ascii=False, indent=2, sort_keys=True))
            return
        if args.lean_dest is None or args.verso_dest is None or (
            args.clean_git_rev is None and not args.derive_clean_rev
        ):
            raise MaterializationError(
                "--lean-dest and --verso-dest are required; provide --clean-git-rev "
                "or use --derive-clean-rev with --init-git"
            )
        report = materialize(
            args.lean_dest,
            args.verso_dest,
            args.clean_git_url,
            args.clean_git_rev,
            args.verso_git_url,
            args.verso_git_rev,
            dry_run=args.dry_run,
            init_git=args.init_git,
            derive_clean_rev=args.derive_clean_rev,
        )
        print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
    except MaterializationError as error:
        raise SystemExit(f"materialization error: {error}") from error


if __name__ == "__main__":
    main()
