/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter5.DiscussionProofOfTheorem546

#doc (Manual) "Prime-power conjugacy classes: proof" =>

# Prime-power conjugacy classes: proof
%%%
tag := "Chapter5/Discussion_proof_of_Theorem5.4.6"
number := false
%%%

Now pick $`V \in N` such that $`\chi_V(g) \neq 0`; it exists by Lemma 5.4.7. Theorem 5.4.4 implies that $`g` (and hence any element of $`C`) acts by a scalar in $`V`. Now let $`H` be the subgroup of $`G` generated by elements $`ab^{-1}`, $`a, b \in C`. It is normal and acts trivially in $`V`, so $`H \neq G`, as $`V` is nontrivial. Also $`H \neq 1`, since $`|C| > 1`. $`\square`

## Formalization
%%%
tag := "Chapter5/Discussion_proof_of_Theorem5.4.6/formalization"
number := false
%%%

### Primary declarations

{Manual.docstring RepresentationTheory.FiniteGroupCharacterCoprimality.character_eq_zero_or_action_eq_smul_id_of_conjClassCard_coprime_finrank}

### Supporting declarations

{Manual.docstring RepresentationTheory.FiniteGroup.PrimePowerConjugacyClass.exists_simple_representation_of_conj_class_card_prime_pow}

{Manual.docstring RepresentationTheory.FiniteGroupNormalSubgroups.exists_nontrivial_proper_normalSubgroup_of_conjClassCard_eq_prime_pow}
