/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter5.Lemma5183

#doc (Manual) "Pure powers and diagonal generators" =>

# Pure powers and diagonal generators
%%%
tag := "Chapter5/Lemma5.18.3"
number := false
%%%

*Lemma 5.18.3.* _Let $`k` be a field of characteristic zero._

_(i) For any finite dimensional vector space $`U` over $`k`, the space $`S^n U` is spanned by elements of the form $`u \otimes \cdots \otimes u`, $`u \in U`._

_(ii) For any algebra $`A` over $`k`, the algebra $`S^n A` is generated by elements $`\Delta_n(a)`, $`a \in A`._

*Proof.* (i) The space $`S^n U` is an irreducible representation of $`GL(U)` (Problem 4.12.3). The subspace spanned by $`u \otimes \cdots \otimes u` is a nonzero subrepresentation, so it must be everything.

(ii) By the fundamental theorem on symmetric functions, there exists a polynomial $`P` with rational coefficients such that

$$`P(H_1(x), \ldots, H_n(x)) = x_1 \ldots x_n`

(where $`x = (x_1, \ldots, x_n)`). Then

$$`P(\Delta_n(a), \Delta_n(a^2), \ldots, \Delta_n(a^n)) = a \otimes \cdots \otimes a.`

The rest follows from (i). $`\square`

## Formalization
%%%
tag := "Chapter5/Lemma5.18.3/formalization"
number := false
%%%

### Primary declarations

{Manual.docstring RepresentationTheory.PiTensorProduct.Constructions.piTensorSubalgebra_eq_alternate}

{Manual.docstring RepresentationTheory.PiTensorProduct.Constructions.span_symmetricPowerSubset_eq_top}
