/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter5.Problem5242

#doc (Manual) "Matrix invariants from traces" =>

# Matrix invariants from traces
%%%
tag := "Chapter5/Problem5.24.2"
number := false
%%%

*Problem 5.24.2.* Let $`R_{k,N}` be the algebra of polynomials on the space of $`k`-tuples of complex $`N \times N` matrices $`X_1, \ldots, X_k`, invariant under simultaneous conjugation. An example of an element of $`R_{k,N}` is the function $`T_w := \operatorname{Tr}(w(X_1, \ldots, X_k))`, where $`w` is any finite word on a $`k`-letter alphabet. Show that $`R_{k,N}` is generated by the elements $`T_w`.

Hint: Consider invariant functions that are of degree $`d_i` in each $`X_i`, and realize this space as a tensor product $`\bigotimes_i S^{d_i}(V \otimes V^*)`. Then embed this tensor product into $`(V \otimes V^*)^{\otimes n} = \operatorname{End}(V)^{\otimes n}`, and use the Schur-Weyl duality to get the result.

## Formalization
%%%
tag := "Chapter5/Problem5.24.2/formalization"
number := false
%%%

### Primary declarations

{Manual.docstring RepresentationTheory.TraceAlgebra.Generation.adjoin_range_eq_designated_subalgebra}

### Supporting declarations

{Manual.docstring RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.complexSubalgebra}

{Manual.docstring RepresentationTheory.Algebra.MvPolynomial.WeightedComponents.NatPairIndexedType.listIndexedElement}
