/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter5.Theorem5182

#doc (Manual) "The enveloping-algebra action" =>

# The enveloping-algebra action
%%%
tag := "Chapter5/Theorem5.18.2"
number := false
%%%

*Theorem 5.18.2.* _The algebra $`B = \operatorname{End}_A E` is the image of the universal enveloping algebra $`\mathcal{U}(\mathfrak{gl}(V))` under its natural action on $`E`. In other words, $`B` is generated by elements of the form_

$$`\Delta_n(b) := b \otimes 1 \otimes \cdots \otimes 1 + 1 \otimes b \otimes \cdots \otimes 1 + \cdots + 1 \otimes 1 \otimes \cdots \otimes b,`

$`b \in \mathfrak{gl}(V)`.

*Proof.* Clearly, the image of $`\mathcal{U}(\mathfrak{gl}(V))` is contained in $`B`, so we just need to show that any element of $`B` is contained in the image of $`\mathcal{U}(\mathfrak{gl}(V))`. By definition, $`B = S^n \operatorname{End} V`, so the result follows from part (ii) of the following lemma.

## Formalization
%%%
tag := "Chapter5/Theorem5.18.2/formalization"
number := false
%%%

### Primary declarations

{Manual.docstring RepresentationTheory.AuxiliaryEndomorphismActions.centralizer_auxiliarySubalgebra_eq_range_universalEnvelopingAlgebraHom}
