import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter3.Problem395

#doc (Manual) "The Clifford algebra" =>

# The Clifford algebra
%%%
tag := "Chapter3/Problem3.9.5"
number := false
%%%
*Problem 3.9.5. The Clifford algebra.* Let $`V` be a finite dimensional complex vector space equipped with a symmetric bilinear form $`( \ , \ )`. The *Clifford algebra* $`\operatorname{Cl}(V)` is the quotient of the tensor algebra $`TV` by the ideal generated by the elements $`v \otimes v - (v, v)1`, $`v \in V`. More explicitly, if $`x_i`, $`1 \leq i \leq N`, is a basis of $`V` and $`(x_i, x_j) = a_{ij}` then $`\operatorname{Cl}(V)` is generated by $`x_i` with defining relations

$$`x_i x_j + x_j x_i = 2a_{ij}, \quad x_i^2 = a_{ii}.`

Thus, if $`( \ , \ ) = 0`, $`\operatorname{Cl}(V) = \wedge V`.

(i) Show that if $`( \ , \ )` is nondegenerate, then $`\operatorname{Cl}(V)` is semisimple and has one irreducible representation of dimension $`2^n` if $`\dim V = 2n` (so in this case $`\operatorname{Cl}(V)` is a matrix algebra) and two such representations if $`\dim(V) = 2n + 1` (i.e., in this case $`\operatorname{Cl}(V)` is a direct sum of two matrix algebras).

Hint: In the even case, pick a basis $`a_1, \ldots, a_n, b_1, \ldots, b_n` of $`V` in which $`(a_i, a_j) = (b_i, b_j) = 0`, $`(a_i, b_j) = \delta_{ij}/2`, and construct a representation of $`\operatorname{Cl}(V)` on $`S := \wedge(a_1, \ldots, a_n)` in which $`b_i` acts as "differentiation" with respect to $`a_i`. Show that $`S` is irreducible. In the odd case the situation is similar, except there should be an additional basis vector $`c` such that $`(c, a_i) = (c, b_i) = 0`, $`(c, c) = 1` and the action of $`c` on $`S` may be defined either by $`(-1)^{\text{degree}}` or by $`(-1)^{\text{degree}+1}`, giving two representations $`S_+, S_-` (why are they nonisomorphic?).
Show that there is no other irreducible representations by finding a spanning set of $`\operatorname{Cl}(V)` with $`2^{\dim V}` elements.

(ii) Show that $`\operatorname{Cl}(V)` is semisimple if and only if $`( \ , \ )` is nondegenerate. If $`( \ , \ )` is degenerate, what is $`\operatorname{Cl}(V)/\operatorname{Rad}(\operatorname{Cl}(V))`?
