import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Discussion24Heading

#doc (Manual) "Section 2.4 Ideals \u2014 heading and definitions" =>
# Section 2.4 Ideals — heading and definitions
%%%
tag := "Chapter2/Discussion_2.4_heading"
number := false
%%%

## 2.4. Ideals
%%%
tag := "Chapter2/Discussion_2.4_heading/heading-1"
%%%

A *left ideal* of an algebra $`A` is a subspace $`I \subseteq A` such that $`aI \subseteq I` for all $`a \in A`. Similarly, a *right ideal* of an algebra $`A` is a subspace $`I \subseteq A` such that $`Ia \subseteq I` for all $`a \in A`. A *two-sided ideal* is a subspace that is both a left and a right ideal.

Left ideals are the same as subrepresentations of the regular representation $`A`. Right ideals are the same as subrepresentations of the regular representation of the opposite algebra $`A^{\mathrm{op}}`.

Below are some examples of ideals:

- If $`A` is any algebra, $`0` and $`A` are two-sided ideals. An algebra $`A \neq 0` is called *simple* if $`0` and $`A` are its only two-sided ideals.
- If $`\phi : A \to B` is a homomorphism of algebras, then $`\ker \phi` is a two-sided ideal of $`A`.
- If $`S` is any subset of an algebra $`A`, then the two-sided ideal *generated* by $`S` is denoted by $`\langle S \rangle` and is the span of elements of the form $`asb`, where $`a, b \in A` and $`s \in S`. Similarly, we can define $`\langle S \rangle_\ell = \operatorname{span}\{as\}` and $`\langle S \rangle_r = \operatorname{span}\{sb\}`, the left, respectively right, ideal generated by $`S`.
