/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter9.Problem932

#doc (Manual) "An involution and a square-zero generator" =>

# An involution and a square-zero generator
%%%
tag := "Chapter9/Problem9.3.2"
number := false
%%%

*Problem 9.3.2.* Let $`A` be the algebra over complex numbers generated by elements $`g, x` with defining relations $`gx = -xg`, $`x^2 = 0`, $`g^2 = 1`. Find the simple modules, the indecomposable projective modules, and the Cartan matrix of $`A`.

## Formalization
%%%
tag := "Chapter9/Problem9.3.2/formalization"
number := false
%%%

### Primary declarations

{Manual.docstring RepresentationTheory.InvolutiveSquareZeroAlgebra.projectiveFamilyMatrix_eq_ones}

{Manual.docstring RepresentationTheory.InvolutiveSquareZeroAlgebra.simpleModule_equiv_positive_xor_negative}

### Supporting declarations

{Manual.docstring RepresentationTheory.InvolutiveSquareZeroAlgebra.finiteProjective_equiv_positive_or_negativeProjective}

{Manual.docstring RepresentationTheory.InvolutiveSquareZeroAlgebra.negativeProjective_projectiveCoverProperties}

{Manual.docstring RepresentationTheory.InvolutiveSquareZeroAlgebra.not_equiv_both_simpleModules}

{Manual.docstring RepresentationTheory.InvolutiveSquareZeroAlgebra.positiveProjective_projectiveCoverProperties}

{Manual.docstring RepresentationTheory.InvolutiveSquareZeroAlgebra.projectiveFamily_existsUnique_equiv}

{Manual.docstring RepresentationTheory.InvolutiveSquareZeroAlgebra.simpleModule_equiv_positive_or_negative}
