import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Discussion210Heading

#doc (Manual) "Section 2.10: Historical interlude \u2014 Sophus Lie's trials and transformations" =>
# Section 2.10: Historical interlude — Sophus Lie's trials and transformations
%%%
tag := "Chapter2/Discussion_2.10_heading"
number := false
%%%

## 2.10. Historical interlude: Sophus Lie's trials and transformations
%%%
tag := "Chapter2/Discussion_2.10_heading/heading-1"
%%%

To call Sophus Lie (1842–1899) an overachiever would be an understatement. Scoring first at the 1859 entrance examinations to the University of Christiania (now Oslo) in Norway, he was determined to finish first as well. When problems with his biology class derailed this project, Lie received only the second-highest graduation score. He became depressed, suffered from insomnia, and even contemplated suicide. At that time, he had no desire to become a mathematician. He began working as a mathematics tutor to support himself, read more and more on the subject, and eventually began publishing research papers. He was 26 when he finally decided to devote himself to mathematics.

The Norwegian government realized that the best way to educate their promising scientists was for them to leave Norway, and Lie received a fellowship to travel to Europe. Lie went straight to Berlin, a leading European center of mathematical research, but the mathematics practiced by local stars — Weierstrass and Kronecker — did not impress him. There Lie met young Felix Klein, who eagerly shared this sentiment. The two had a common interest in line geometry and became friends. Klein's and Lie's personalities complemented
each other very well. As the mathematician Hans Freudenthal put it, "Lie and Klein had quite different characters as humans and mathematicians: the algebraist Klein was fascinated by the peculiarities of charming problems; the analyst Lie, parting from special cases, sought to understand a problem in its appropriate generalization" \[*16*, p. 323\].

Lie liked to bounce ideas off his friend's head, and Klein's returns were often quite powerful. In particular, Klein pointed out an analogy between Lie's research on the tetrahedral complex and the Galois theory of commutative permutation groups. Blissfully unaware of the difficulties on his path, Lie enthusiastically embraced this suggestion. Developing a continuous analog of the Galois theory of algebraic equations became Lie's _idée fixe_ for the next several years.

Lie and Klein traveled to Paris together, and there Lie produced the famous contact transformation, which mapped straight lines into spheres. An application of this expertise to the Earth sphere, however, did not serve him well. After the outbreak of the Franco-Prussian war, Lie could not find a better way to return to Norway than by first hiking to Italy. With his peculiar hiking habits, such as taking off his clothes in the rain and putting them into his backpack, he was not able to flee very far. The French quickly apprehended him and found papers filled with mysterious symbols. Lie's efforts to explain the meaning of his mathematical notation did not dispel the authorities' suspicion that he was a German spy. A short stay in prison afforded him some quiet time to complete his studies, and upon return to Norway, Lie successfully defended his doctoral dissertation. Unable to find a job in Norway, Lie resolved to go to Sweden, but Norwegian patriots intervened, and the Norwegian National Assembly voted by a large majority to establish a personal extraordinary professorship for Lie at the University of Christiania. Although the salary offered was less than extraordinary, he stayed.

Lie's research on sphere mapping and his lively exchanges with Klein led both of them to think of more general connections between group theory and geometry. In 1872 Klein presented his famous Erlangen Program, in which he suggested unifying specific geometries under a general framework of projective geometry and using group
theory to organize all geometric knowledge. Lie and Klein clearly articulated the notion of a transformation group, the continuous analog of a permutation group, with promising applications to geometry and differential equations, but they lacked a general theory of the subject. The Erlangen Program implied one aspect of this project — the group classification problem — but Lie had no intention of attacking this bastion at the time. As he later wrote to Klein, "\[I\]n your essay the problem of determining _all_ groups is not posited, probably on the grounds that at the time such a problem seemed to you absurd or impossible, as it did to me" \[*22*, pp. 41–42\].

By the end of 1873, Lie's pessimism gave way to a much brighter outlook. After dipping into the theory of first order differential equations, developed by Jacobi and his followers, and making considerable advances with his _idée fixe_, Lie finally acquired the mathematical weaponry needed to answer the challenge of the Erlangen Program and to tackle the theory of continuous transformation groups.

Living on the outskirts of Europe, Lie felt quite marginalized in the European mathematics community. No students and very few foreign colleagues were interested in his research. He wrote his papers in German but published them almost exclusively in Norwegian journals, preferring publication speed over wide accessibility. A few years later he learned, however, that one French mathematician had won the _Grand Prix_ from the Académie des Sciences for independently obtained results that yielded some special cases of Lie's work on differential equations. Lie realized that his Norwegian publications were not the greatest publicity vehicle, and that he needed to make his work better known in Europe. "If only I could collect together and edit all my results," he wistfully wrote to Klein \[*22*, p. 77\]. Klein's practical mind quickly found a solution. Klein, who then taught at Leipzig, arranged for the young mathematician Friedrich Engel, a recent doctoral student of his colleague, to go to Christiania and to render Lie a helping mathematical hand.

Lie and Engel met twice daily for a polite conversation about transformation groups. As Engel recalled, Lie carried his theory almost entirely in his head and dictated to Engel an outline of each chapter, "a sort of skeleton, to be clothed by me with flesh and blood"
\[*22*, p. 77\]. Lie read and revised Engel's notes, eventually producing the first draft of a book-length manuscript.

When Klein left Leipzig to take up a professorship at Göttingen, he arranged for the vacated chair of geometry to be offered to Lie. Lie somewhat reluctantly left his homeland and arrived at Leipzig with the intention of building "a healthy mathematical school" there \[*22*, p. 226\]. He continued his collaboration with Engel, which culminated in the publication of their joint three-volume work, _Theorie der Transformationsgruppen_.

Lie's ideas began to spread around Europe, finding a particularly fertile ground in Paris. Inspired by Lie, Henri Poincaré remarked that all mathematics was a tale about groups, and Émile Picard wrote to Lie, "Paris is becoming a center for groups; it is all fermenting in young minds, and one will have an excellent wine after the liquors have settled a bit". German mathematicians were less impressed. Weierstrass believed that Lie's theory lacked rigor and had to be rebuilt from the foundations, and Frobenius labeled it a "theory of methods" for solving differential equations in a roundabout way, instead of the natural methods of Euler and Lagrange \[*22*, pp. 186, 188–189\].

Students flocked to Lie's lectures on his own research, but this only exacerbated his heavy teaching load at Leipzig — 8–10 lectures per week — compared to the leisurely pace of his work in Christiania. An outdoor man, who was used to weeks-long hikes in Norway, Lie felt homesick, longing for the forests and mountains of his native country. All this began taking its toll on Lie. Most importantly, he felt underappreciated and became obsessed with the idea that others plundered his work and betrayed his trust. His relations with colleagues gradually deteriorated, particularly with those closest to him. He broke with Engel and eventually with Klein. Lie felt that his role in the development of the Erlangen Program was undervalued, and he publicly attacked Klein, claiming, "I am no pupil of Klein, nor is the opposite the case, although this might be closer to the truth. I value Klein's talent highly and will never forget the sympathetic interest with which he has always followed my scientific endeavors. But I do
not feel that he has a satisfactory understanding of the difference between induction and proof, or between a concept and its application" \[*56*, p. 371\]. Whoever was right in this dispute, Lie's public accusations against widely respected and influential Klein reflected badly on Lie's reputation.

Eventually Lie suffered a nervous breakdown and was diagnosed with "neurasthenia", a popular mental disease dubbed the "American Nervousness", or "Americanitis". Its cause was ascribed to the stress of modern urban life and the exhaustion of an individual's "nervous energy". Lie spent some months in the supposedly less stressful environment of a psychiatric clinic and upon some reflection decided that he was better off in his mathematics department. His mathematical abilities returned, but his psyche never fully recovered. Rumors spread of his mental illness, possibly fueled by his opponents, who tried to invalidate his accusations.

In the meantime, trying to assert its cultural (and eventually political) independence from Sweden, Norway took steps to bring back its leading intellectuals. The Norwegian National Assembly voted to establish a personal chair in transformation group theory for Lie, matching his high Leipzig salary. Lie was anxious to return to his homeland, but his wife and three children did not share his nostalgia. He eventually returned to Norway in 1898 with only a few months to live.

Lie "thought and wrote in grandiose terms, in a style that has now gone out of fashion, and that would be censored by our scientific journals", wrote one commentator \[*26*, p. iii\]. Lie was always more concerned with originality than with rigor. "Let us reason with concepts!" he often exclaimed during his lectures and drew geometrical pictures instead of providing analytical proofs \[*22*, p. 244\]. "Without Phantasy one would never become a Mathematician", he wrote. "\[W\]hat gave me a Place among the Mathematicians of our Day, despite my Lack of Knowledge and Form, was the Audacity of my Thinking" \[*56*, p. 409\]. Hardly lacking relevant knowledge, Lie indeed had trouble putting his ideas into publishable form. Due to Engel's diligence, Lie's research on transformation groups was summed up in three grand volumes, but Lie never liked this ghost-written work
