import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter4.Problem4128

#doc (Manual) "Classification of finite subgroups of SO(3) and SU(2)" =>

# Classification of finite subgroups of SO(3) and SU(2)
%%%
tag := "Chapter4/Problem4.12.8"
number := false
%%%

*Problem 4.12.8.* It is known that the classification of finite subgroups of $`SO(3)` is as follows:

1) the cyclic group $`\mathbb{Z}/n\mathbb{Z}`, $`n \geq 1`, generated by a rotation by $`2\pi/n` around an axis;

2) the dihedral group $`D_n` of order $`2n`, $`n \geq 2` (the group of rotational symmetries in 3-space of a plane containing a regular $`n`-gon[^Chapter4/Problem4.12.8/footnote-2];

3) the group of rotations of a regular tetrahedron ($`A_4`);

4) the group of rotations of a cube or regular octahedron ($`S_4`);

5) the group of rotations of a regular dodecahedron or icosahedron ($`A_5`).

(a) Derive this classification.

Hint: Let $`G` be a finite subgroup of $`SO(3)`. Consider the action of $`G` on the unit sphere. A point of the sphere preserved by some nontrivial element of $`G` is called a pole. Show that every nontrivial element of $`G` fixes a unique pair of opposite poles and that the subgroup of $`G` fixing a particular pole $`P` is cyclic, of some order $`m` (called the order of $`P`). Thus the orbit of $`P` has $`n/m` elements, where $`n = |G|`. Now let $`P_1, \ldots, P_k` be a collection of poles representing all the orbits of $`G` on the set of poles (one representative per orbit), and let $`m_1, \ldots, m_k` be their orders. By counting nontrivial elements of $`G`, show that

$$`2\left(1 - \frac{1}{n}\right) = \sum_i \left(1 - \frac{1}{m_i}\right).`

Then find all possible $`m_i` and $`n` that can satisfy this equation and classify the corresponding groups.

[^Chapter4/Problem4.12.8/footnote-2]: A regular 2-gon is just a line segment.

(b) Using this classification, classify finite subgroups of $`SU(2)` (use the homomorphism $`SU(2) \to SO(3)`).
