import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Example2913

#doc (Manual) "Universal enveloping algebra of the Heisenberg Lie algebra" =>
# Universal enveloping algebra of the Heisenberg Lie algebra
%%%
tag := "Chapter2/Example2.9.13"
number := false
%%%
*Example 2.9.13.* The algebra $`U(\mathcal{H})`, where $`\mathcal{H}` is the Heisenberg Lie algebra, is the algebra generated by $`x`, $`y`, $`c` with the relations

$$`yx - xy = c, \qquad yc - cy = 0, \qquad xc - cx = 0.`

Note that the Weyl algebra is the quotient of $`U(\mathcal{H})` by the relation $`c = 1`.
