import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Problem286

#doc (Manual) "Generators and relations for the path algebra" =>
# Generators and relations for the path algebra
%%%
tag := "Chapter2/Problem2.8.6"
number := false
%%%
*Problem 2.8.6.* Show that for a finite quiver $`Q` the algebra $`P_Q` is generated by $`p_i` for $`i \in I` and $`a_h` for $`h \in E` with the following defining relations:

(1) $`\sum_{i \in I} p_i = 1`,

(2) $`p_i^2 = p_i`, $`p_i p_j = 0` for $`i \neq j`,

(3) $`a_h p_{h'} = a_h`, $`a_h p_j = 0` for $`j \neq h'`,

(4) $`p_{h''} a_h = a_h`, $`p_i a_h = 0` for $`i \neq h''`.
