import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter3.Problem392

#doc (Manual) "Ext^1 for polynomial algebras and algebras with zero multiplication" =>

# Ext^1 for polynomial algebras and algebras with zero multiplication
%%%
tag := "Chapter3/Problem3.9.2"
number := false
%%%
*Problem 3.9.2.* (a) Let $`A = \mathbb{C}[x_1, \ldots, x_n]`, and let $`V_a, V_b` be 1-dimensional representations in which the elements $`x_i` act by $`a_i` and $`b_i`, respectively ($`a_i, b_i \in \mathbb{C}`). Find $`\operatorname{Ext}^1(V_a, V_b)` and classify 2-dimensional representations of $`A`.

(b) Let $`B` be the algebra over $`\mathbb{C}` generated by $`x_1, \ldots, x_n` with the defining relations $`x_i x_j = 0` for all $`i, j`. Show that for $`n > 1` the algebra $`B` has infinitely many nonisomorphic indecomposable representations.
