import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Problem2165

#doc (Manual) "Quantum enveloping algebra U\\_q(sl(2)) and its irreducible representations" =>
# Quantum enveloping algebra U\_q(sl(2)) and its irreducible representations
%%%
tag := "Chapter2/Problem2.16.5"
number := false
%%%
*Problem 2.16.5.* Let $`k` be an algebraically closed field of characteristic zero, and let $`q \in k^\times`, $`q \neq \pm 1`. The quantum enveloping algebra $`\mathcal{U}_q(\mathfrak{sl}(2))` is the algebra generated by $`e, f, K, K^{-1}` with relations

$$`KeK^{-1} = q^2 e, \quad KfK^{-1} = q^{-2} f, \quad [e, f] = \frac{K - K^{-1}}{q - q^{-1}}`

(if you formally set $`K = q^h`, you'll see that this algebra, in an appropriate sense, "degenerates" to $`\mathcal{U}(\mathfrak{sl}(2))` as $`q \to 1`). Classify irreducible
representations of $`\mathcal{U}_q(\mathfrak{sl}(2))`. Consider separately the cases of $`q` being a root of unity and $`q` not being a root of unity.
