import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Example2912

#doc (Manual) "Universal enveloping algebra of sl(2)" =>
# Universal enveloping algebra of sl(2)
%%%
tag := "Chapter2/Example2.9.12"
number := false
%%%
*Example 2.9.12.* The associative algebra $`U(\mathfrak{sl}(2))` is the algebra generated by $`e`, $`f`, $`h`, with relations

$$`he - eh = 2e, \qquad hf - fh = -2f, \qquad ef - fe = h.`
