/-
Copyright (c) 2026 American Mathematical Society. All rights reserved.
-/

import VersoManual
import RepresentationTheory

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter3.Problem392

#doc (Manual) "Ext¹ for polynomial algebras and square-zero relations" =>

# Ext¹ for polynomial algebras and square-zero relations
%%%
tag := "Chapter3/Problem3.9.2"
number := false
%%%
*Problem 3.9.2.* (a) Let $`A = \mathbb{C}[x_1, \ldots, x_n]`, and let $`V_a, V_b` be 1-dimensional representations in which the elements $`x_i` act by $`a_i` and $`b_i`, respectively ($`a_i, b_i \in \mathbb{C}`). Find $`\operatorname{Ext}^1(V_a, V_b)` and classify 2-dimensional representations of $`A`.

(b) Let $`B` be the algebra over $`\mathbb{C}` generated by $`x_1, \ldots, x_n` with the defining relations $`x_i x_j = 0` for all $`i, j`. Show that for $`n > 1` the algebra $`B` has infinitely many nonisomorphic indecomposable representations.

## Formalization
%%%
tag := "Chapter3/Problem3.9.2/formalization"
number := false
%%%

### Primary declarations

{Manual.docstring RepresentationTheory.Algebra.Module.PolynomialEvaluationModules.auxiliaryType_subsingleton_of_ne}

{Manual.docstring RepresentationTheory.Algebra.Module.PolynomialEvaluationModules.nonempty_auxiliaryType_linearEquiv}

{Manual.docstring RepresentationTheory.Algebra.Module.TwoDimensionalPolynomialModules.finrank_two_linearEquiv_prod_or_dualNumberModule}

{Manual.docstring RepresentationTheory.Algebra.Module.TwoDimensionalPolynomialModules.nonempty_linearEquiv_iff}

{Manual.docstring RepresentationTheory.Algebra.Module.TwoDimensionalPolynomialModules.nonempty_prod_evaluationModule_linearEquiv_iff}

{Manual.docstring RepresentationTheory.Algebra.Module.TwoDimensionalPolynomialModules.not_nonempty_prod_linearEquiv_dualNumberModule_of_ne}

### Supporting declarations

{Manual.docstring RepresentationTheory.Algebra.Module.PolynomialEvaluationModules.AuxiliaryAlgebra}

{Manual.docstring RepresentationTheory.Algebra.Module.PolynomialEvaluationModules.EvaluationModule}

{Manual.docstring RepresentationTheory.Algebra.Module.PolynomialEvaluationModules.PolynomialAlgebra}

{Manual.docstring RepresentationTheory.Algebra.Module.PolynomialEvaluationModules.exists_evaluation_submodule_and_quotient_of_finrank_two}

{Manual.docstring RepresentationTheory.Algebra.Module.PolynomialEvaluationModules.exists_pairwise_nonisomorphic_auxiliaryModules}

{Manual.docstring RepresentationTheory.Algebra.Module.PolynomialEvaluationModules.smul_eq_aeval_smul}
