import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Definition299

#doc (Manual) "Universal enveloping algebra" =>
# Universal enveloping algebra
%%%
tag := "Chapter2/Definition2.9.9"
number := false
%%%
*Definition 2.9.9.* Let $`\mathfrak{g}` be a Lie algebra with basis $`x_i` and $`[\ ,\ ]` defined by $`[x_i, x_j] = \sum_k c^k_{ij} x_k`. The *universal enveloping algebra* $`U(\mathfrak{g})` is the associative algebra generated by the $`x_i`'s with the defining relations $`x_i x_j - x_j x_i = \sum_k c^k_{ij} x_k`.
