import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Problem2163

#doc (Manual) "Lie algebras defined by ad relations" =>
# Lie algebras defined by ad relations
%%%
tag := "Chapter2/Problem2.16.3"
number := false
%%%
*Problem 2.16.3.* (Hard!) For any element $`x` of a Lie algebra $`\mathfrak{g}` let $`\operatorname{ad}(x)` denote the operator $`\mathfrak{g} \to \mathfrak{g}`, $`y \mapsto [x, y]`. Consider the Lie algebra $`\mathfrak{g}_n` generated by two elements $`x, y` with the defining relations $`\operatorname{ad}(x)^2(y) = \operatorname{ad}(y)^{n+1}(x) = 0`.

(a) Show that the Lie algebras $`\mathfrak{g}_1, \mathfrak{g}_2, \mathfrak{g}_3` are finite dimensional and find their dimensions.

(b) (Harder!) Show that the Lie algebra $`\mathfrak{g}_4` has infinite dimension. Construct explicitly a basis of this algebra.
