import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Discussion29LieGroups

#doc (Manual) "Linear algebraic groups, Lie groups, and Lie's correspondence" =>
# Linear algebraic groups, Lie groups, and Lie's correspondence
%%%
tag := "Chapter2/Discussion_2.9_Lie_groups"
number := false
%%%
The most important examples of Lie groups are *linear algebraic groups*, which are subgroups of $`GL_n(\mathbb{R})` defined by algebraic equations (such as, for example, the group of orthogonal matrices $`O_n(\mathbb{R})`).

Also, given a Lie subalgebra $`\mathfrak{g} \subset \mathfrak{gl}_n(\mathbb{R})` (which, by Ado's theorem, can be any finite dimensional real Lie algebra), we can define $`G` to be the subgroup of $`GL_n(\mathbb{R})` generated by the elements $`e^X`, $`X \in \mathfrak{g}`. One can show that this group has a natural structure of a connected Lie group, whose Lie algebra is $`\mathfrak{g}` (even though it is not always a closed subgroup). While this group is not always simply connected, its universal covering $`\widetilde{G}` is, and it is the Lie group corresponding to $`\mathfrak{g}` under Lie's correspondence.

For more on Lie groups and their relation to Lie algebras, the reader is referred to textbooks on this subject, e.g. \[*Ki*\].
