import VersoManual

open Verso.Genre Manual

namespace IntroductionToRepresentationTheoryVerso.Content.Chapter2.Exercise2112

#doc (Manual) "Equivalent definition of tensor product via free abelian group" =>
# Equivalent definition of tensor product via free abelian group
%%%
tag := "Chapter2/Exercise2.11.2"
number := false
%%%
*Exercise 2.11.2.* Show that $`V \otimes W` can be equivalently defined as the quotient of the free abelian group $`V \bullet W` generated by $`v \otimes w`, $`v \in V, w \in W` by the subgroup generated by

$$`(v_1 + v_2) \otimes w - v_1 \otimes w - v_2 \otimes w,`
$$`v \otimes (w_1 + w_2) - v \otimes w_1 - v \otimes w_2,`
$$`av \otimes w - v \otimes aw,`

where $`v \in V, w \in W, a \in k`.
